### PR TITLE
Fix broken IGV.xml generation

### LINKED ISSUE #81: IGV.xml has too ".//" in the middle of the URL for resources, resulting in 404s where there should be  data

### PR DESCRIPTION
**Pull request by ihodes**
Construct paths without extraneous separators

Somewhat janky fix for now. Some more elegant would improve how we construct paths.

fixes #81

### CODE REVIEW

File: src/lib/final_report.ml [hunk 1]
```diff
@@ -291,9 +291,16 @@ module To_workflow
     let product =
       (single_file ~host (Config.saving_path // sprintf "index.html")) in
     let opt_prefix p =
-      match igv_url_server_prefix with
+      let open Option in
+      (* Want to make sure we don't end up with a url like http://example.com/./something *)
```
Comment (armish) [inline src/lib/final_report.ml:295]: OOC: IGV can't handle those URLs or is it the Google Cloud URLs that are breaking if you have that `/./`?

**Review by armish — APPROVED** [review]
👍

**Comment by ihodes** [comment]
Google Cloud is breaking/an extra / in the path refers to a different
resource (that probably can't even exist), somehow…
